### PR TITLE
Migrate dataset

### PR DESCRIPTION
**Pull request by CanerIrfanoglu**
Issue for app: #15 

# App pull request
- [ ] This is a new app
- [x] I am improving an existing app (redesigns/code "makeovers")

## About

- Playground deployment URL (new version):
- Current gallery app URL: (delete this line if inapplicable)
- Python app repository link: (delete this line if you are working on a Python app)

## Workflow

- [x] I have created a branch in the appropriate monorepo, and the
  elements necessary for successful deployment are in place.
- [ ] If the app is a redesigned and/or restyled version of an
  existing gallery app, I've summarized the changes requested in the
  appropriate Streambed issue and confirm that they have been applied.
- [ ] If the app is on the Dash Gallery portal, I have added a link to
  the GitHub repository for the source code in the portal description.
- [x] If the app is a reimplementation of a Python gallery app for the
  DashR gallery, the app in this PR mimics, as closely as possible,
  the style and functionality of the existing app.=
- [x] I have removed *all Google Analytics code* from the app's
  `assets/` folder.

## The pre-review review

I have addressed all of the following questions:

- [x] Does everything in my code serve some purpose? (I have removed
  any dead and/or irrelevant code.)
- [x] Does everything in my code have a clear purpose? (My code is
  readable and, where it isn't, it has been commented appropriately.)]
- [x] Am I reinventing the wheel? (I have used appropriate packages to
  lessen the volume of code that needs to be maintained.)

### CODE REVIEW

**Comment by CanerIrfanoglu** [comment]
Tried to stop Git LFS from tracking by doing `git lfs uninstall ` and by removing git LFS from `.gitattributes`. However, noticed the data files are still tracked when pushing the branch. Opened it as a **draft** pull request and will convert to a pull request after figuring out how to stop Git LFS from tracking.

**Comment by rpkyle** [comment]
> Tried to stop Git LFS from tracking by doing `git lfs uninstall ` and by removing git LFS from `.gitattributes`. However, noticed the data files are still tracked when pushing the branch. Opened it as a **draft** pull request and will convert to a pull request after figuring out how to stop Git LFS from tracking.

@CanerIrfanoglu Let's avoid making any configuration changes to the repository, definitely don't edit anything in `.git` -- but I wanted to share the results of my search. Is it possible that `git` set these hooks when `git-lfs` was enabled?

If you look inside `dash-sample-apps/.git/hooks`, you'll see

```
post-checkout:2:command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n"; exit 2; }
post-checkout:3:git lfs post-checkout "$@"
post-commit:2:command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.\n"; exit 2; }
post-commit:3:git lfs post-commit "$@"
post-merge:2:command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-merge.\n"; exit 2; }
post-merge:3:git lfs post-merge "$@"
pre-push:2:command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
pre-push:3:git lfs pre-push "$@"
```

@shammamah @nicolaskruchten

**Comment by CanerIrfanoglu** [comment]
When I ran `git lfs track` on my local branch, I found the deleted files are still followed:
```
Caners-MBP:dash-sample-apps Caner$ git lfs track
Listing tracked patterns
    data/output.csv (.gitattributes)
    output.csv (.gitattributes)
```
Then I ran following commands:
```
git lfs untrack data/output.csv
git lfs untrack output.csv
```
which resulted in:
```
Untracking "./data/output.csv"
Untracking "output.csv"
```
Afterwards I found the `.gitattributes ` is modified as follows:
Screen Shot 2019-06-29 at 7 15 00 PM

Finally when I pushed these changes, the commit went quickly, whereas I had to wait longer when files tracked earlier. 

It seems like the files had to be untracked individually rather than trying to modify `.gitattributes` manually.

@rpkyle the changes are ready for your review.

**Comment by rpkyle** [comment]
@CanerIrfanoglu Interesting. Worth a try; @nicolaskruchten @shammamah what do you think? I say let’s 💃 and hope this fixes it.

**Comment by shammamah** [comment]
@rpkyle This looks like it should fix our issue. @CanerIrfanoglu thanks for getting this done so quickly!

**Comment by rpkyle** [comment]
:dancer:

**Pull request merged**
