### PR TITLE
dash brain viewer

### PR DESCRIPTION
**Pull request by chriskfwoo**
Issue for app: #24 

# App pull request
- [ ] This is a new app
- [x] I am improving an existing app (redesigns/code "makeovers")

## About

- Playground deployment URL (new version): https://dash-playground.plotly.host/dash-brain-viewer/
- Current gallery app URL: https://dash-gallery.plotly.host/dash-brain-surface-viewer/

## Workflow

- [x] I have created a branch in the appropriate monorepo, and the
  elements necessary for successful deployment are in place.
- [x] If the app is a redesigned and/or restyled version of an
  existing gallery app, I've summarized the changes requested in the
  appropriate Streambed issue and confirm that they have been applied.
- [ ] If the app is on the Dash Gallery portal, I have added a link to
  the GitHub repository for the source code in the portal description.
- [ ] If the app is a reimplementation of a Python gallery app for the
  DashR gallery, the app in this PR mimics, as closely as possible,
  the style and functionality of the existing app.=
- [x] I have removed *all Google Analytics code* from the app's
  `assets/` folder.

## The pre-review review

I have addressed all of the following questions:

- [x] Does everything in my code serve some purpose? (I have removed
  any dead and/or irrelevant code.)
- [x] Does everything in my code have a clear purpose? (My code is
  readable and, where it isn't, it has been commented appropriately.)]
- [x] Am I reinventing the wheel? (I have used appropriate packages to
  lessen the volume of code that needs to be maintained.)

### CODE REVIEW

**Comment by chriskfwoo** [comment]
## Style changes

Sidebar
- made it fixed and scrollable if overflows
- left-aligned subtitles

## Mobile Layout 

brain-mobile

**Comment by chriskfwoo** [comment]
I'm not sure if there's a better way to save custom annotations. 

I have a function called `save_annotations()` that listens to the `relayout_data` and I able to get that edit
annotation text by getting the key `scene.annotations[0].text` in the relayout_data. I store the key and text value in the dcc store dictionnary.

Essentially, I have a dictionary that contains `"scene.annotations[index_of_list].text"` as keys. And, I have to store each text in the appropriate index in the figure list `figure["layout"]["scene"]["annotations"][index]["text"]`.

The difficult part is that the path to the text is coded in the string in the key: `"scene.annotations[index_of_list].text"`.

**Comment by chriskfwoo** [comment]
> Screen Shot 2019-06-18 at 3 46 27 PM
> 
> This looks quite a bit darker than what's in the mockup -- did you use Avocode to get the color codes?

Good call. See [commit](https://github.com/plotly/dash-sample-apps/pull/148/commits/205287faf6990b1aa54c39b90ea871d6c6e0994c).

**Comment by chriskfwoo** [comment]
> The double scroll bar style on the right side looks kind of weird.
> 
> scroll bars

This is a small edge case where the graph is too big (this will only happen on really low-resolution screens). I would think of a solution.

> Annotation text goes outside of the box. Maybe add a overflow scroll for the annotations?
> 
> annotation text

This is the same behaviour currently on the gallery. The text only appears outside of the box only when you are editing. I don't think this is a problem.

**Comment by chriskfwoo** [comment]
@shammamah @ronniebugia please review my latest changes 😄

**Comment by shammamah** [comment]
@chriskfwoo Did you remove the ability to add annotations? I'm not able to do so any more

**Comment by chriskfwoo** [comment]
> @chriskfwoo Did you remove the ability to add annotations? I'm not able to do so any more

I added an issue about loading time for annotations. https://github.com/plotly/dash-sample-apps/issues/173

Let me know if there's any other request changes.

**Pull request merged**
