### PR TITLE
Add pileup demo (#minor)

### PR DESCRIPTION
**Pull request by akmorrow13**
Issue for app: #[issue number here]

# App pull request
- [x] This is a new app
- [ ] I am improving an existing app (redesigns/code "makeovers")

## About

- Playground deployment URL (new version):
- Current gallery app URL: (delete this line if inapplicable)
- Python app repository link: (delete this line if you are working on a Python app)

## Workflow

- [x] I have created a branch in the appropriate monorepo, and the
  elements necessary for successful deployment are in place.
- [ ] If the app is a redesigned and/or restyled version of an
  existing gallery app, I've summarized the changes requested in the
  appropriate Streambed issue and confirm that they have been applied.
- [ ] If the app is on the Dash Gallery portal, I have added a link to
  the GitHub repository for the source code in the portal description.
- [ ] If the app is a reimplementation of a Python gallery app for the
  DashR gallery, the app in this PR mimics, as closely as possible,
  the style and functionality of the existing app.=
- [ ] I have removed *all Google Analytics code* from the app's
  `assets/` folder.

## The pre-review review

I have addressed all of the following questions:

- [ ] Does everything in my code serve some purpose? (I have removed
  any dead and/or irrelevant code.)
- [ ] Does everything in my code have a clear purpose? (My code is
  readable and, where it isn't, it has been commented appropriately.)]
- [ ] Am I reinventing the wheel? (I have used appropriate packages to
  lessen the volume of code that needs to be maintained.)

## Post PR (at merge time)

- [ ] When you are merging, make sure to write one of the following tags in the commit message (or it will default to patch):
  - `#patch` - An app has been updated or fixed
  - `#minor` - A new app has been added, or an app has been significantly reworked
  - `#major` - Breaking changes, make sure to discuss with dash-core before using this tag

### CODE REVIEW

**Comment by akmorrow13** [comment]
@xhlulu replaces https://github.com/plotly/dash-sample-apps/pull/601 I did not have permissions to push to the current branch.
Waiting on https://github.com/plotly/dash-bio/pull/554 so we can fix the volcano layout.

**Comment by xhlulu** [comment]
Sure, this works for me

**Comment by HammadTheOne** [comment]
cc @akmorrow13 @xhlulu 

plotly/dash-bio#554 has been merged into the master branch. You should now able to set any layout params of the VolcanoPlot figure as arbitrary keys. There's still a couple of things left before I make the `dash-bio-0.7.0` release to `PyPi`, but in the meantime you can just add this to `requirements.txt` to install the package directly from the git repo:
```
git+git://github.com/plotly/dash-bio.git@master
```

Let me know if you run into any trouble.

**Comment by akmorrow13** [comment]
Thanks @HammadTheOne! I think we need the demo up by April 22nd. Will we be able to merge everything in by then to get the pileup demo up?

**Comment by HammadTheOne** [comment]
@akmorrow13 Yes, we'll definitely have everything ready by then.

**Comment by xhlulu** [comment]
let me know if there's anything i can do to help.

@akmorrow13 It doesn't seem CI can be triggered by non-circleci members. when it's ready, let me know and i'll push to this branch so it triggers the deployment.

**Comment by akmorrow13** [comment]
@xhlulu I pushed the styling update for volcano plots and added dash-bio master in requirements, as @HammadTheOne suggested. It should now be ready. I just added you as a collaborator to my repository.

**Comment by xhlulu** [comment]
@akmorrow13 I can't trigger circleci on this fork so i'll just merge it to the original PR and work that one.

**Pull request merged**
