### PR TITLE
[sample-apps] Fixed issue #357

### PR DESCRIPTION
**Pull request by oxananu**
Small fix for Issue #357 for app dash-nlp

### CODE REVIEW

**Comment by lundstrj** [comment]
@ycaokris looks OK. Are you OK with merging it?

**Comment by ycaokris** [comment]
Seems circle-ci is halt but changes looks good 👍

**Comment by ycaokris** [comment]
@lundstrj  feel free to get this merged.

**Comment by lundstrj** [comment]
already added in a different merge. Not relevant anymore.

**Pull request closed without merging**
