### PR TITLE
Optimize csv files

### PR DESCRIPTION
**Pull request by xhlulu**
See issue: https://github.com/plotly/dash-sample-apps/issues/649

### CODE REVIEW

**Comment by xhlulu** [comment]
@HammadTheOne Hey can you review commits https://github.com/plotly/dash-sample-apps/pull/659/commits/c2a9f7b8c79e1b81522729367e3de72151dedba9 to https://github.com/plotly/dash-sample-apps/pull/659/commits/2efbe81287232fd75130d132cac46403dd833809? Just want to make sure it will work for the dashr app

**Comment by HammadTheOne** [comment]
:woman_dancing:

**Review by HammadTheOne — APPROVED** [review]
LGTM - All apps are deployed successfully and able to read and access data from the now compressed `csv.gz` files. 

:woman_dancing:

**Comment by xhlulu** [comment]
Just fixed food-footprint. Should be good now

**Pull request merged**
