### PR TITLE
Removing color picker and adjusting css. Also, Robs first commit

### PR DESCRIPTION
**Pull request by AirballClaytonCalvin**
Issue for app: https://github.com/plotly/dash-sample-apps/issues/412

# App pull request
- [ ] This is a new app
- [x] I am improving an existing app (redesigns/code "makeovers")

## About

- Playground deployment URL (new version): https://dash-playground.plotly.host/dash-daq-tektronix350/
- Current gallery app URL: https://dash-gallery.plotly.host/dash-daq-tektronix350/

## Workflow

- [x] I have created a branch in the appropriate monorepo, and the
  elements necessary for successful deployment are in place.
- [ ] If the app is a redesigned and/or restyled version of an
  existing gallery app, I've summarized the changes requested in the
  appropriate Streambed issue and confirm that they have been applied.
- [x] If the app is on the Dash Gallery portal, I have added a link to
  the GitHub repository for the source code in the portal description.
- [ ] If the app is a reimplementation of a Python gallery app for the
  DashR gallery, the app in this PR mimics, as closely as possible,
  the style and functionality of the existing app.=
- [ ] I have removed *all Google Analytics code* from the app's
  `assets/` folder.

## The pre-review review

I have addressed all of the following questions:

- [x] Does everything in my code serve some purpose? (I have removed
  any dead and/or irrelevant code.)
- [x] Does everything in my code have a clear purpose? (My code is
  readable and, where it isn't, it has been commented appropriately.)]
- [x] Am I reinventing the wheel? (I have used appropriate packages to
  lessen the volume of code that needs to be maintained.)

### CODE REVIEW

**Comment by sstripps1** [comment]
💃 looks good to me

**Comment by lundstrj** [comment]
I'll try to take a look tomorrow. Sorry to be the one holding up the progress.

**Comment by lundstrj** [comment]
I was going to look at this but I think I stumbled over a requirements conflict.
requirements.txt states:
```
gunicorn==19.9.0
dash==1.0.0
numpy==1.16.1
scipy==1.2.1
dash-daq==0.3.0

```
But dash-daq 0.3.0 demands dash 1.6.2 or greater
`ERROR: dash-daq 0.3.0 has requirement dash>=1.6.0, but you'll have dash 1.0.0 which is incompatible.`

I can't install the dependencies for this app as things are stated right now. How did you guys do it?

**Comment by lundstrj** [comment]
Okay, so I ignored the requirements.txt for now and just got the latest and greatest of all dependencies (seems to run OK like that).

I think the PR seems to work as intended.

💃

**Comment by lundstrj** [comment]
@AirballClaytonCalvin do you want to do the honors and merge this into master?

**Pull request merged**
