### PR TITLE
ct exploration app

### PR DESCRIPTION
**Pull request by emmanuelle**
# App pull request
- [x] This is a new app
- [ ] I am improving an existing app (redesigns/code "makeovers")

## About

- Playground deployment URL (new version):
- Current gallery app URL: (delete this line if inapplicable)
- Python app repository link: (delete this line if you are working on a Python app)

## Workflow

- [ ] I have created a branch in the appropriate monorepo, and the
  elements necessary for successful deployment are in place.
- [ ] If the app is a redesigned and/or restyled version of an
  existing gallery app, I've summarized the changes requested in the
  appropriate Streambed issue and confirm that they have been applied.
- [ ] If the app is on the Dash Gallery portal, I have added a link to
  the GitHub repository for the source code in the portal description.
- [ ] If the app is a reimplementation of a Python gallery app for the
  DashR gallery, the app in this PR mimics, as closely as possible,
  the style and functionality of the existing app.=
- [ ] I have removed *all Google Analytics code* from the app's
  `assets/` folder.

## The pre-review review

I have addressed all of the following questions:

- [ ] Does everything in my code serve some purpose? (I have removed
  any dead and/or irrelevant code.)
- [ ] Does everything in my code have a clear purpose? (My code is
  readable and, where it isn't, it has been commented appropriately.)]
- [ ] Am I reinventing the wheel? (I have used appropriate packages to
  lessen the volume of code that needs to be maintained.)

### CODE REVIEW

**Comment by emmanuelle** [comment]
I will need a deployment of this app for the webinar but this is not ready yet to be reviewed.

**Comment by emmanuelle** [comment]
@nicholas-esterer I finally finished a version of the app with which I'm happy :-). Please review when you have the time; I'm interested in knowing whether it's clear what to do from the different titles of figures, or whether more explanations should be added.

**Comment by nicholas-esterer** [comment]
(Sorry I accidentally posted this in the wrong place before):
Hmm I'm trying to review the PR and after making the venv and installing the requirements, running with `python app.py` or `gunicorn app:server`, the app looks like this:
Screenshot from 2020-09-24 12-28-13
Maybe something is missing? :thinking:

**Comment by emmanuelle** [comment]
Hum, thanks for reporting this. On playground it looks like this
image

Could you please try with the most recent stable version of Dash? Maybe I need to pin its version because it will only work with the most recent stable Dash.

**Comment by nicholas-esterer** [comment]
Yes that fixed it. I just ran `pip install -U dash`. The specific version is `dash==1.16.1`.

**Comment by nicholas-esterer** [comment]
As for the use of the app, it's pretty slick! I like that you can experiment with different selections of the histogram values, to see how that changes the selection.
A couple things that might be a little unclear to new users:
- the shapes drawn on the images stay when you scroll to other slices of the image, is that because they extend the full length of the image in the direction normal (in the linear algebra sense) to the shape? If so maybe some clarification is needed?
- I'm not sure if I can go back and edit the shapes and have the final result updated. For example if I try and erase the shapes after having chosen histogram values, they don't seem to erase... If users really need to do the process in order, maybe steps could be "greyed" out before one is allowed to proceed to them?

**Comment by emmanuelle** [comment]
Thanks for the review Nick! Yes, annotations persist because the volume considered for the histogram segmentation is the "extrusion" of the closed path drawn on the left image, between heights defined by the rectangle drawn on the right image. This is a bit tricky to explain but I'll try to find a way to make this clearer. Also I agree that going back to correct annotations does not work well, I'll look into this.

**Comment by emmanuelle** [comment]
@nicholas-esterer I have made the following changes
- it is now possible to modify a shape (one has to re-select a range in the histogram)
- I've added tooltips (with `dbc.Tooltip`) to add more explanations about the shapes to draw

**Comment by nicholas-esterer** [comment]
Cool! It seems there is a small bug when drawing a rectangle in the 2nd figure from bottom to top: in that case the 'y0' and 'y1' points of the rectangle are switched. But I have a two-line fix to this problem (just sort the values before choosing top and bottom), should I just push it to this PR?

**Comment by emmanuelle** [comment]
@nicholas-esterer thanks for noticing this bug! Yes please push a commit to this PR, thanks a lot!

**Comment by nicholas-esterer** [comment]
I think I fixed it for when the users input funny shapes (upside down rectangles or shapes that are too small so that the slice indices for the start and end are the same).
I thought it might be nice to be able to delete the rectangle in the right pane, could "erase active shape" be enabled for this pane?

**Comment by emmanuelle** [comment]
Thanks @nicholas-esterer ! I updated the modebar buttons so that the two views are more symmetric (one is for closed path and the other one for a rectangle, but shapes can be erased in both figures).

**Comment by emmanuelle** [comment]
anything else I should do here @nicholas-esterer ?

**Comment by nicholas-esterer** [comment]
One small thing might be to reset the found 3D shape (display no red) if one of the shapes changes. This will sort of demonstrate that the user needs to select the histogram values again (because they changed) and that the current selections don't represent the 3D shape displayed. Or you could just write that in one of the "?" parts. But this is a minor thing, the app is working really well! I'll :woman_dancing: this in case you want to get it merged ASAP :-)

**Review by nicholas-esterer — APPROVED** [review]

**Review by nicholas-esterer — APPROVED** [review]
That's looking great! My only nitpicky comment would be that although the red is erased on the 3D figure when the shapes are changed, the red is not erased on the 2D figure whose shape was not edited. So that would be a minor thing to improve. But otherwise it is really great! :woman-dancing:

**Pull request merged**
