### PR TITLE
Use smaller dataset

### PR DESCRIPTION
**Pull request by tarzzz**
Issue for app: #333 

# App pull request
- [x] I am improving an existing app (redesigns/code "makeovers")

Specifying `2` in the prompt allows us to download the 10K dataset instead of the default 7M dataset.

### CODE REVIEW

**Comment by tarzzz** [comment]
@cldougl Please review.. As discussed, I have updated the omnisci deployment to use "10K" dataset instead of "7M". 

I have also increased resources on cluster (RAM increased from 4GB to 16GB) which should help with the performance.

**Comment by tarzzz** [comment]
cc: @ycaokris .. !!

**Comment by cldougl** [comment]
@tarzzz I've approved the pr already but 💃 if you were waiting

**Comment by tarzzz** [comment]
I was waiting for Kris actually:
image

but it seems that is not required.. Merging..

**Pull request merged**
