### PR TITLE
Dash drug discovery

### PR DESCRIPTION
**Pull request by chriskfwoo**
Issue for app: #22

# App pull request
- [ ] This is a new app
- [x] I am improving an existing app (redesigns/code "makeovers")

## About

- Playground deployment URL (new version): https://dash-playground.plotly.host/dash-drug-discovery/
- Current gallery app URL: https://dash-gallery.plotly.host/dash-drug-discovery/

## Workflow

- [x] I have created a branch in the appropriate monorepo, and the
  elements necessary for successful deployment are in place.
- [x] If the app is a redesigned and/or restyled version of an
  existing gallery app, I've summarized the changes requested in the
  appropriate Streambed issue and confirm that they have been applied.
- [ ] If the app is on the Dash Gallery portal, I have added a link to
  the GitHub repository for the source code in the portal description.
- [ ] If the app is a reimplementation of a Python gallery app for the
  DashR gallery, the app in this PR mimics, as closely as possible,
  the style and functionality of the existing app.

## The pre-review review

I have addressed all of the following questions:

- [x] Does everything in my code serve some purpose? (I have removed
  any dead and/or irrelevant code.)
- [x] Does everything in my code have a clear purpose? (My code is
  readable and, where it isn't, it has been commented appropriately.)]
- [x] Am I reinventing the wheel? (I have used appropriate packages to
  lessen the volume of code that needs to be maintained.)

### CODE REVIEW

**Comment by chriskfwoo** [comment]
## Desktop
image

## Mobile
image

**Comment by chriskfwoo** [comment]
> The font for the header appears to be different in the mockup. Other than that, 💃

My default font is `font-family: "Open Sans", sans-serif`. Do you know what font-family it's using? It looks like a `serif`. Times New Roman? 

Will it be weird to use different types of font-family?

**Comment by chriskfwoo** [comment]
@shammamah @ronniebugia please review my latest [commit](https://github.com/plotly/dash-sample-apps/pull/108/commits/5925abc25af1d64b0a420e8734eb54d4d55b69e5) 😀

**Comment by shammamah** [comment]
@angeladaodao Could you please post the name of the font used in this app? 

I think it looks fine now -- we can always go back and change the exact font later. For now, it looks great. 💃

**Pull request merged**
