### PR TITLE
Dashr volcanoplot

### PR DESCRIPTION
**Pull request by sacul-git**
Issue for app: #[issue number here]

# App pull request
- [x] This is a new app
- [ ] I am improving an existing app (redesigns/code "makeovers")

## About

- Playground deployment URL (new version):
- Current gallery app URL: (https://dash-bio.plotly.host/dash-volcano-plot/)
- Python app repository link: (https://github.com/plotly/dash-bio/blob/master/tests/dashbio_demos/app_volcano_plot.py)

## Workflow

- [x] I have created a branch in the appropriate monorepo, and the
  elements necessary for successful deployment are in place.
- [ ] If the app is a redesigned and/or restyled version of an
  existing gallery app, I've summarized the changes requested in the
  appropriate Streambed issue and confirm that they have been applied.
- [ ] If the app is on the Dash Gallery portal, I have added a link to
  the GitHub repository for the source code in the portal description.
- [x] If the app is a reimplementation of a Python gallery app for the
  DashR gallery, the app in this PR mimics, as closely as possible,
  the style and functionality of the existing app.=
- [x] I have removed *all Google Analytics code* from the app's
  `assets/` folder.

## The pre-review review

I have addressed all of the following questions:

- [x] Does everything in my code serve some purpose? (I have removed
  any dead and/or irrelevant code.)
- [x] Does everything in my code have a clear purpose? (My code is
  readable and, where it isn't, it has been commented appropriately.)]
- [x] Am I reinventing the wheel? (I have used appropriate packages to
  lessen the volume of code that needs to be maintained.)

### CODE REVIEW

**Comment by sacul-git** [comment]
This app functions properly, but uses some workarounds to get the volcanoplot to work: There are some inconsistencies with the way `dashbioVolcano` works in `R` relative to `dashbio.VolcanoPlot`, namely the use of `effect_size`. `effect_size` in python accepts a string argument, which is the column name that contains the effect sizes for each observation. This is an argument in `volcanor` (one of the functions `dashbioVolcano` depends on), but does not get passed in `dashbioVolcano`. As a workaround, I changed the column name to `EFFECTSIZE` (the default value). 

There are also some issues with the hover and click data, which I can't access properly in `dashbioVolcano`. It looks like there was a lot of work done on [the python side](https://github.com/plotly/dash-bio/blob/1a250d6f70e1492d425f2a588a92f2650895df46/dash_bio/component_factory/_volcano.py#L14-L50) to get the hover data working properly, which did not get translated over to `R`, since `dashbioVolcano` wraps `manhattanly` functions to create the figure.

**Comment by rpkyle** [comment]
@sacul-git Fixing now; will update when done.

**Comment by rpkyle** [comment]
> There are also some issues with the hover and click data, which I can't access properly in `dashbioVolcano`. It looks like there was a lot of work done on [the python side](https://github.com/plotly/dash-bio/blob/1a250d6f70e1492d425f2a588a92f2650895df46/dash_bio/component_factory/_volcano.py#L14-L50) to get the hover data working properly, which did not get translated over to `R`, since `dashbioVolcano` wraps `manhattanly` functions to create the figure.

@sacul-git Can you open an issue via https://github.com/sahirbhatnagar/manhattanly summarizing the latter comments, maybe with a minimal example (if you've got one, otherwise no worries).

**Comment by rpkyle** [comment]
> This app functions [almost] properly, but uses some workarounds to get the volcanoplot to work: There are some inconsistencies with the way `dashbioVolcano` works in `R` relative to `dashbio.VolcanoPlot`, namely the use of `effect_size`. `effect_size` in python accepts a string argument, which is the column name that contains the effect sizes for each observation. This is an argument in `volcanor` (one of the functions `dashbioVolcano` depends on), but does not get passed in `dashbioVolcano`. As a workaround, I changed the column name to `EFFECTSIZE` (the default value).

@sacul-git As we discussed offline, I think this may have to do with the way `...` arguments are processed inside the `manhattanly` package. In the case of `volcanoly`, I'm not sure they're processed at all, depending on how the function is called 😅 

I've raised an issue with Sahir to investigate. For now, let's use your workaround.

I don't want to break `dashbioVolcano` so that it works around what I hypothesize is unintended behaviour from a dependent package, I'd rather refactor the app when we've sorted this out.

https://github.com/sahirbhatnagar/manhattanly/issues/21#issue-463320443

**Pull request merged**
