### PR TITLE
Canvas annotation app

### PR DESCRIPTION
**Pull request by ycaokris**
Issue for app: #https://github.com/plotly/dash-customer-success/issues/255

# App pull request
- [x] This is a new app
- [ ] I am improving an existing app (redesigns/code "makeovers")

## About

- Playground deployment URL (new version): https://dash-playground.plotly.host/dash-canvas-ocr/
- Current gallery app URL: https://dash-gallery.plotly.host/dash-canvas-ocr/

## Workflow

- [ ] I have created a branch in the appropriate monorepo, and the
  elements necessary for successful deployment are in place.
- [ ] If the app is a redesigned and/or restyled version of an
  existing gallery app, I've summarized the changes requested in the
  appropriate Streambed issue and confirm that they have been applied.
- [ ] If the app is on the Dash Gallery portal, I have added a link to
  the GitHub repository for the source code in the portal description.
- [ ] If the app is a reimplementation of a Python gallery app for the
  DashR gallery, the app in this PR mimics, as closely as possible,
  the style and functionality of the existing app.=
- [ ] I have removed *all Google Analytics code* from the app's
  `assets/` folder.

## The pre-review review

I have addressed all of the following questions:

- [ ] Does everything in my code serve some purpose? (I have removed
  any dead and/or irrelevant code.)
- [ ] Does everything in my code have a clear purpose? (My code is
  readable and, where it isn't, it has been commented appropriately.)]
- [ ] Am I reinventing the wheel? (I have used appropriate packages to
  lessen the volume of code that needs to be maintained.)

### CODE REVIEW

**Comment by ycaokris** [comment]
> Is it okay if the layout doesn't resize properly when the window size decreases?
> 
> Screen Shot 2020-02-28 at 5 45 48 PM
> 
> Apart from that minor issue, 💃

Good catch. I'll need a release of dash Canvas for implementing responsiveness. Once this PR is merged https://github.com/plotly/dash-canvas/pull/39

**Comment by lundstrj** [comment]
@sstripps1 you worked on this, right? Looks like. this got stuck in code review.
What is your take, should this get merged as is or should we dive in and examine this app more closely? My understanding is that this was more of a tech demo we did for a specific occasion, is that correct?

**Comment by sstripps1** [comment]
@lundstrj this app is good to go other than a mobile responsiveness bug, which will be resolved once https://github.com/plotly/dash-canvas/pull/39 is merged and we can use an updated version of canvas. Although we could probably merge for now (since it's mostly just for demo purposes anyway) and then add in that fix at a later date.

**Comment by lundstrj** [comment]
okay, cool. Someone will have to run black on this and then we'll merge then.

I suppose I could do that. unless... @AirballClaytonCalvin

**Comment by AirballClaytonCalvin** [comment]
Happy to 'run black on this'. Although not 100% sure what that means.

**Comment by sstripps1** [comment]
@AirballClaytonCalvin I can walk you thru it 💯

**Comment by AirballClaytonCalvin** [comment]
@sstripps1 I ran Black and it made 1 minor change to the app.py file. However, when I run it locally after the update, I get a callback error in my browser. 

'Callback error updating text-output.children'

I am struggling to troubleshoot it right now.

**Comment by AirballClaytonCalvin** [comment]
💃

**Pull request merged**
