### PR TITLE
Add flake8 to CircleCI and enable rule E711.

### PR DESCRIPTION
**Pull request by jbampton**
Comparison to none should be 'if cond is none:'.

Lint Python code for rule E711.

https://www.flake8rules.com/rules/E711.html

### CODE REVIEW

**Comment by lundstrj** [comment]
This looks like a straight forward enough PR. We should be able to take care of it relatively shortly.

**Comment by lundstrj** [comment]
@josegonzalez Hey man, what do you think about this one?

**Comment by josegonzalez** [comment]
Seems reasonable to me. Any reason why we wouldn't want to apply _all_ of the flake8 rules, @jbampton ? Other than maybe the number of code changes (which is reasonable).

**Comment by lundstrj** [comment]
Good enough for @josegonzalez is good enough for me.

**Pull request merged**
